### ISSUE TITLE
unicode in .less breaks

### ISSUE THREAD

**Issue by ghost** [andreyfedoseev/django-less#4]
I know that using non ascii characters in css iles is rare but it is allowed and I had to do just that, sadly it breaks
offending line is located in less/templatetags/less.py:

``` python
    compiled_file = open(output_path, "w+")
    compiled_file.write(URLConverter(out, os.path.join(STATIC_URL, path)).convert())
```

I don't know how to repair it though

the error reads: 

```
'ascii' codec can't decode byte
```

css can be anything with non ascii, mine is

``` css
 .external_link:first-child:before {
    content:"Zobacz także:";
}
```
